title: Haotian Yan's Homepage
page-top-title: Haotian Yan
top-section-bg-text: Traditional Chinese Medical Science
home-subtitle: Haotian Yan&ensp;|&ensp;颜浩天
copyright-text: '&copy; Haotian Yan 2023-2024. All Rights Reserved.'
